### ISSUE TITLE
Building custom Django Middleware

### ISSUE THREAD

**Issue by Priyal-Trivedi** [PyLadiesDelhi/talks#1]
Talk shall cover the following topics:
- Introduction to Django Middlewares
- Understanding the working of it 
- Creating a custom middleware 
- Explaining with an example

**Comment by utkarsh2102** [comment]
Hi @Priyal-Trivedi,
Was there any presentation slide or video?
If yes, please share it's link asap :)

**Comment by Priyal-Trivedi** [comment]
Slides - https://slides.com/priyaltrivedi-1/tmux_terminal_multiplexer
