### ISSUE TITLE
Introduction HTML5 and CSS3

### ISSUE THREAD

**Issue by sakshikul** [PyLadiesDelhi/talks#12]
**Abstract**

Descriptions of content shall be covered.
. Introduction of HTML5 and CSS3.
. Structure of HTML.
. HTML tags and CSS property.

Level: Beginner

What will be needed? just a text editor(sublime).

**Comment by utkarsh2102** [comment]
Hi @sakshikul.
Are you available on 18th August?

**Comment by utkarsh2102** [comment]
Hi,
Are you available for a talk on the 8th of September?
