### ISSUE TITLE
Building cross-browser tests for the web-platform

### ISSUE THREAD

**Issue by Cactusmachete** [PyLadiesDelhi/talks#15]
**Abstract**

Since the development of the world's second web-browser, there has been a growing need for web-standards. Coordinated by the W3C, web-platform-tests  is an attempt to build a cross-browser testsuite for the Web-platform stack.

**About**

A brief introduction to web-platform-tests, their purpose, how they're used and how they work. 

**Pre-requisites**

- Git
- Basic knowledge of Python/HTML/JS

**Expected duration**

20-25 minutes.

**Level**

Beginner

**Resources**

https://github.com/web-platform-tests/wpt

**Speaker Bio**

A third year CSE undergrad at IIITD, I've been a regular contributor over at web-platform-tests and Mozilla. 

**Resources**
[Slides](https://docs.google.com/presentation/d/1L4l7kHBB5R-JD7lQrDo18fi7GZAHKN8DvyTKAeHjJqk/edit?usp=sharing)

**Comment by utkarsh2102** [comment]
Hi @Cactusmachete,
Are you available for a talk on 18th August?

**Comment by Cactusmachete** [comment]
Hi @utkarsh2102, I am :)

**Comment by utkarsh2102** [comment]
Awesome! :D
I'm scheduling the same.

**Comment by utkarsh2102** [comment]
Can you please share the slides?

**Comment by utkarsh2102** [comment]
Thank you for the talk, @Cactusmachete.
Looking forward for more :D
