### ISSUE TITLE
Python 101

### ISSUE THREAD

**Issue by pulkitpahwa** [PyLadiesDelhi/talks#2]
Python 101

Python 101 will be a 4-hour python workshop which aims to teach python from scratch. Attempts will be made to make it more and more hands-on. I shall be talking about the following topics:

1. Variables and data types : Strings, Integers, etc.
2. Data structures :  Lists, sets, tuples.
3. Conditions : if-else
4. Loops : for loops and while loops
5. Functions

You might want to go through this book: http://pymbook.readthedocs.io/en/latest/

Prerequisites:
A laptop with python installed is recommended.

**Comment by utkarsh2102** [comment]
Hi @pulkitpahwa,
Was there any presentation slide or video?
If yes, please share it's link asap :)
