### ISSUE TITLE
Playing around with Adobe XD

### ISSUE THREAD

**Issue by grlwholifts** [PyLadiesDelhi/talks#22]
This talk will familiarize you with various tools and tricks of designing apps and websites using Adobe XD 

**About**
Starting off with a know-how-it-works session and the basics of prototyping and testing, this talk would help you design a basic landing page for your app/website. 

**Pre-requisites**
- Adobe XD in your machine
- A calm mind to think, non sticky fingers to type 

**Expected duration**
45-60 minutes

**Level**
Beginner

**Resources**
Download UI kit here: [Wires.zip](https://github.com/PyLadiesDelhi/talks/files/3576168/Wires.zip)
Download Adobe XD here: [Adobe XD](https://www.adobe.com/in/products/xd.html)

**Speaker Bio**
Hey there! I'm on a hunt for new design ideas. Will probably steal yours. Attend this talk, get marked and stay safe!

**Comment by mridubhatnagar** [comment]
Hi @ruchikabgosain, thank you for volunteering to give a talk. Developers learning design skills would be fun. Looking forward to your hands-on session on 5th October.

**Comment by utkarsh2102** [comment]
Hi!
If this session is done, would you be interested in making a PR, adding your name and details to the `README.md`?

**Comment by utkarsh2102** [comment]
Once the details are merged, I'll add `Completed` label here.

**Comment by grlwholifts** [comment]
sure, I will do that @utkarsh2102 🍎

**Comment by utkarsh2102** [comment]
Thank you!
