### ISSUE TITLE
Android with Kotlin - 101

### ISSUE THREAD

**Issue by sakshivij** [PyLadiesDelhi/talks#23]
**Abstract**

The talks revolves around how to get started with Kotlin, android studio and how we can create an application using Kotlin.

**About**

Introduction to Kotlin

Need for Kotlin instead of Java

Basic syntax and how to create programs in it.

Introduction to Android Studio 

Demo of 

- creating a basic Counter android application using Kotlin as language 
- using maps in the Android App

**Pre-requisites**

- Basic Java knowledge good to have

- Java and Android Studio needs to be installed

**Expected duration**

60 min

**Level**

Beginner

**Resources**

**Speaker Bio**

I am Sakshi Vij,  currently pursuing masters from IGDTUW. I have organised various events and love working for the community. I love teaching and have been a freelance teacher for more than a year now. I recently started contributing towards open Source. I am a mentor at coding Coach and Skillship Foundation. I have a passion to teach, share and help others grow. 
###### - Can be done after the talk/workshop -

[Include link to slides here](link)

[Include link to video here](link)

**Comment by mridubhatnagar** [comment]
Hi @sakshivij 

Would you be giving only the demo? Or the audience would be developing the application along with you hands-on?

**Comment by sakshivij** [comment]
It's a demo+hands-on

**Comment by utkarsh2102** [comment]
Hi!
If this session is done, would you be interested in making a PR, adding your name and details to the `README.md`?

**Comment by sakshivij** [comment]
No. It will be done in upcoming meetup. But will do the needful after.

**Comment by utkarsh2102** [comment]
Great, thank you!
