### ISSUE TITLE
#IamRemarkable Session on Ada Lovelace Day

### ISSUE THREAD

**Issue by knowShubhangi** [PyLadiesDelhi/talks#24]
**Abstract**
Topic - #IamRemarkable

**About**
This is an initiative by Google to help women self promote and gain self-confidence.

**Pre-requisites**
None. 

**Expected duration**
30 - 45 mins

**Level**
Non-Technical Workshop.

**Resources**
https://iamremarkable.withgoogle.com/

**Speaker Bio**
I am Shubhangi, I am the core of DSC IGDTUW and an active volunteer in GDG New Delhi. I am a trained IamRemarkable Facilitator and an MLH facilitator. I am also a Microsoft Student Partner.
Please refer to this https://www.linkedin.com/in/shubhangi0304/ for more details.

###### - Can be done after the talk/workshop -

[Include link to slides here](link) - Cannot be shared

[Include link to video here](link) - None.

**Comment by mridubhatnagar** [comment]
Hey @Shubhangi0304 

Thank you for volunteering as a speaker. The intent seems interesting to me. However, I just have one question. Does the session involve explicitly encouraging women or it can be made generic?

I personally have no issues with having this as a talk. But, I am not very sure on how audience is going to perceive it. I don't want the positive intent of your talk taken in a negative manner by someone else.

**Comment by knowShubhangi** [comment]
The talk can be altered for heterogenous attendees.

**Comment by mridubhatnagar** [comment]
Great! Looking forward to your session on 5th October  :)

**Comment by utkarsh2102** [comment]
Hi!  
If this session is done, would you be interested in making a PR, adding your name and details to the `README.md`?

**Comment by knowShubhangi** [comment]
Yeah sure

**Comment by utkarsh2102** [comment]
@Shubhangi0304, whenever you raise a PR, let me know.  
I'll merge and add a tag of `Completed` here.  

Also, thank you for your talk! :)

**Comment by knowShubhangi** [comment]
I have raised a PR

**Comment by knowShubhangi** [comment]
Thanks !

**Comment by utkarsh2102** [comment]
Merged, thank you!  
Looking forward for your next talk! :tada:
