### ISSUE TITLE
Java 101

### ISSUE THREAD

**Issue by Pallavi024** [PyLadiesDelhi/talks#26]
**Abstract**

This talk will guide the attendees through the fundamentals and applications of Java programming language.

**About**

The talk will include the following :-

1) What is Java?
2) History of Java
3) Features of Java
4) C++ vs Java
5) JDK, JRE, JVM
6) Basic syntax, variables, unicode system, operators, keywords, control statements, loops, data structures, packages, access modifiers.
7) OOP concepts in Java
8) Collections in Java
9) Generics in Java
11) Abstract Classes
10) Interfaces
11) Exception Handling in Java
12) Multithreading in Java
13) Applications of Java

**Pre-requisites**

None

**Expected duration**

45 - 60 minutes

**Level**

Beginner

**Speaker Bio**

I am Pallavi Bishnoi, currently pursuing computer science engineering from IGDTUW.  I am an incoming intern at Salesforce, coding mentor at ACM IGDTUW, Google Get Ahead-APAC scholar, React India Conference scholar and Google India scholar. I have experience working in Java and Android projects. I am also a core team member at Women Who Code Delhi.

###### - Can be done after the talk/workshop -

[Include link to slides here](link)

[Include link to video here](link)

**Comment by sakshivij** [comment]
Can we close this ? As we are focusing on python related technologies ?

**Comment by Pallavi024** [comment]
Yes, sure!
