### ISSUE TITLE
Cloud Architecture and Microservices with AWS : An Introduction to the Cloud Era

### ISSUE THREAD

**Issue by yugkhanna** [PyLadiesDelhi/talks#4]
The talk is about how microservices are becoming increasing popular and the breakdown of monolith into microservices using cloud technologies like AWS. It is about services used to automate processes to manage large data and requests at the same time

The talk will be conceptual describing certain tools like EC2, DynamoDB, CloudWatch, API Gateway, RDS, IAM and a few more. All of these services are used to manage a great architecture running on the cloud which empowers our apps. AWS being a front leader in cloud is the most popular in dealing with automated expansion of services. I will be explaining Auto Scaling Groups and Load Balancers and will talk about their processes as well.
Overall the talk should give you a great idea of how cloud technologies work and what services are used behind our backends to make a powerful app run.

There are no pre-requisites as such. It will be a conceptual talk to make everyone understand the services and get started with them using AWS Free Tier

Expected Duration : 30-45 minutes

Level - Beginner - Intermediate 

Resources : "https://aws.amazon.com/getting-started/"

Speaker - Yug Khanna ( I am a student at University of Waterloo, Canada and am here in India for my internship as a DevOps Engineer. I am studying Computer Engineering and have deep passion for ML and Deep Learning)

**Comment by im-gozmit** [comment]
Hi @yugkhanna, 
Are you available for the talk on the 23rd of September?

**Comment by yugkhanna** [comment]
I am not in India.

**Comment by sakshivij** [comment]
Hi @yugkhanna would you be interested in giving a talk on 10th May? Also may be discuss about new technologies in AWS ?

**Comment by yugkhanna** [comment]
Hey,

I’m currently in Canada so I cannot do the talk. I should be back in India
soon so I will get in touch with you guys then.

How does that sound?

Best,
Yug Khanna

**Comment by sakshivij** [comment]
Thanks @yugkhanna though we are doing a virtual meet-up this time. Though I understand the time difference might be one issue. 

Thanks for your reply

**Comment by yugkhanna** [comment]
I’m pretty sure I can adjust the time difference. So we can do the virtual
talk on 10th if that works for you.

Yug

**Comment by yugkhanna** [comment]
We can get on a call to figure this out if you'd like. I’m mainly open to
talk about deep learning and computer vision and talk about the basics.
Lemme know and we can get on a call

Yug

**Comment by sakshivij** [comment]
Sure. Give me sometime to figure things out and will get in touch with you soon!

Thanks. 
Sakshi

**Comment by sakshivij** [comment]
@yugkhanna can you share me your time availability and details on sakshivij12@gmail.com? We can get on a call regarding this then.

**Comment by sakshivij** [comment]
We need to close this issue. @utkarsh2102
