### ISSUE TITLE
Web Scraping 101

### ISSUE THREAD

**Issue by aaqaishtyaq** [PyLadiesDelhi/talks#5]
**Abstract**
This workshop is about what is web scraping and how to do web scraping using Scrapy, one of the popular Python framework for web scraping. 

**About**
This workshop will cover the workflow of scraping a website, step by step.

1) Reconnaissance: After deciding the kind of information we want, We find a page where we can start. We will then inspect the elements that matter to us and find out their tag (div, p, etc) and the class if necessary. Open up a scrapy shell and try to get the information we need, by accessing the corresponding element using XPath. 

2) Crawling: Then, we use this logic in our code, to extract data recursively. Typically we will jump from page to page, by extracting links that match a pattern.

3) Aquisition: During this process, any useful information we need, say text, images, etc, will be downloaded and saved to disk.

**Pre-requisites**
Basic knowledge of HTML and Python would be sufficient.

Those who want to follow along must have Scrapy(1.5.0) installed or if there is internet on the venue(which would be) they can install at that time. It's a pretty minimal install.

**Expected Duration** : ~90 minutes

**Level**: Beginner-Intermediate

**Resources**: "https://doc.scrapy.org/en/latest/index.html"

**Speaker Bio**: Aaqa Ishtyaq (I am final year Computer Science student. Currently doing an internship in Delhi as a Backend Developer)

**Comment by utkarsh2102** [comment]
Hi @aaqaishtyaq.
Thank you for coming up!
I'm confirming your talk/workshop for `7th July, 2018`.
Let me know if you have requirements from our side :)

**Comment by aaqaishtyaq** [comment]
@utkarsh2102 Do you guys have USB Type C to VGA/HDMI, so that my laptop can connect to the projector.

**Comment by utkarsh2102** [comment]
@aaqaishtyaq, we'd definitely arrange that!
Also, text the requirements in the group as a backup :D

**Comment by utkarsh2102** [comment]
Thank you for the great talk, @aaqaishtyaq :D
