### ISSUE TITLE
OSS and Open Source Contribution

### ISSUE THREAD

**Issue by VictoriousAura** [PyLadiesDelhi/talks#7]
**Abstract**
The talk will include all the hype about OSS, Open Source Projects and contributing in it. Students always have confusion and difficulties about how should they start about it. This talk will give them the insights about how to start and what oppurtunities they can find from it. 

**About**

The session will be covered as:
1) Explaining the termonologies : OSS, Open Source, Open Source Projects
       
2) Github : Open Source contribution is incomplete without Version Control system. Taking Github , I 
                  shall talk about it telling the importance and get the audience familiar about some basic 
                  Github Commands.

3) Communities with projects and How to choose : There are numerous communities like Mozilla,                                                                                     
                  Facebook, GGSOC which have open source projects. How to choose a project will be 
                   covered here.

4) Oppurtunities : There are various opputunities one can look for like GSOC, Outreachy , RGSOC, 
                 Fossasia Codeheat and other internship programs.

**Pre-requisites**

Zeal to learn something new

**Expected duration**

30-40 minutes

**Level**

Beginner/Intermediate/Advanced 

**Resources**

https://rubygarage.org/blog/how-contribute-to-open-source-projects

**Speaker Bio**

Shrreya Behll is presently a lead of Developer Student Clubs (DSC) by Google Developers. 
She is an Android enthusiast and working as an android developer at FoodCham Pvt Ltd.
Also she is currently contributing in GSSOC( GirlScript Summer Of Code)
LinkedIn : https://www.linkedin.com/in/shrreyabehll/
Twitter : https://twitter.com/behll_shrreya

**Comment by utkarsh2102** [comment]
Hi @ShrreyaBehll.
Thank you for coming up.
I'm scheduling your talk for `7th July, 2018`.
Is there anything you need from our side?

**Comment by VictoriousAura** [comment]
That's my pleasure! 
Just a VGA to HDMI cable.

**Comment by utkarsh2102** [comment]
@ShrreyaBehll, we'd definitely arrange that!
Also, text the requirements in the group as a backup :D

**Comment by utkarsh2102** [comment]
Thank you for the great talk, @ShrreyaBehll :D
